### ISSUE TITLE
Deleting a category crashes the app

### ISSUE THREAD

**Issue by hankolsen** [taniarascia/takenote#106]
Steps to reproduce:
1. Create a category
2. Click the x icon to delete the category
Result: The screen turns white and the console contains an error message related to Helmet.

```browser.js:34 Uncaught Invariant Violation: Helmet expects a string as a child of <title>. Did you forget to wrap your children in braces? ( <title>{``}</title> ) Refer to our API for more information.
    at invariant (http://localhost:3000/static/js/0.chunk.js:32058:15)
    at o.warnOnInvalidChildren (http://localhost:3000/static/js/0.chunk.js:123453:379)
    at http://localhost:3000/static/js/0.chunk.js:123469:61
    at forEachSingleChild (http://localhost:3000/static/js/0.chunk.js:127793:12)
    at traverseAllChildrenImpl (http://localhost:3000/static/js/0.chunk.js:127687:9)
    at traverseAllChildrenImpl (http://localhost:3000/static/js/0.chunk.js:127703:27)
    at traverseAllChildren (http://localhost:3000/static/js/0.chunk.js:127767:14)
    at Object.forEachChildren [as forEach] (http://localhost:3000/static/js/0.chunk.js:127815:7)
    at o.mapChildrenToProps (http://localhost:3000/static/js/0.chunk.js:123459:66)
    at o.render (http://localhost:3000/static/js/0.chunk.js:123502:27)
    at finishClassComponent (http://localhost:3000/static/js/0.chunk.js:79376:35)
    at updateClassComponent (http://localhost:3000/static/js/0.chunk.js:79331:28)
    at beginWork$1 (http://localhost:3000/static/js/0.chunk.js:81051:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/0.chunk.js:61329:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/0.chunk.js:61378:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/0.chunk.js:61431:35)
    at beginWork$$1 (http://localhost:3000/static/js/0.chunk.js:86677:11)
    at performUnitOfWork (http://localhost:3000/static/js/0.chunk.js:85582:16)
    at workLoopSync (http://localhost:3000/static/js/0.chunk.js:85558:26)
    at performSyncWorkOnRoot (http://localhost:3000/static/js/0.chunk.js:85119:15)
    at http://localhost:3000/static/js/0.chunk.js:73279:28
    at unstable_runWithPriority (http://localhost:3000/static/js/0.chunk.js:133190:16)
    at runWithPriority$2 (http://localhost:3000/static/js/0.chunk.js:73225:14)
    at flushSyncCallbackQueueImpl (http://localhost:3000/static/js/0.chunk.js:73274:11)
    at flushSyncCallbackQueue (http://localhost:3000/static/js/0.chunk.js:73262:7)
    at discreteUpdates$1 (http://localhost:3000/static/js/0.chunk.js:85300:11)
    at discreteUpdates (http://localhost:3000/static/js/0.chunk.js:62451:16)
    at dispatchDiscreteEvent (http://localhost:3000/static/js/0.chunk.js:66915:7)```

**Comment by taniarascia** [comment]
I'll submit a fix shortly.

**Comment by taniarascia** [comment]
Fixed.
