### ISSUE TITLE
[Bug] Fail to build docker (cwebp)

### ISSUE THREAD

**Issue by hube12** [taniarascia/takenote#451]
**To Reproduce**
Steps to reproduce the behavior: docker build . (with NODE_ENV=production)

**Expected behavior**
Should not fail

**Actual behavior**
fail

```sh
Step 7/10 : RUN npm ci --only-production --silent
 ---> Running in 1c89267a05c4

Skipping 'fsevents' build as platform linux is not supported
Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux_musl-x64-72_binding.node
Download complete
Binary saved to /app/node_modules/node-sass/vendor/linux_musl-x64-72/binding.node
Caching binary to /root/.npm/_cacache/node-sass/4.14.1/linux_musl-x64-72_binding.node
Binary found at /app/node_modules/node-sass/vendor/linux_musl-x64-72/binding.node
Testing binary
Binary is fine
  ⚠ Command failed: /app/node_modules/cwebp-bin/vendor/cwebp -version
Error loading shared library libGL.so.1: No such file or directory (needed by /app/node_modules/cwebp-bin/vendor/cwebp)
Error loading shared library libX11.so.6: No such file or directory (needed by /app/node_modules/cwebp-bin/vendor/cwebp)
Error loading shared library libXxf86vm.so.1: No such file or directory (needed by /app/node_modules/cwebp-bin/vendor/cwebp)
Error loading shared library libXi.so.6: No such file or directory (needed by /app/node_modules/cwebp-bin/vendor/cwebp)
Error relocating /app/node_modules/cwebp-bin/vendor/cwebp: __fprintf_chk: symbol not found
Error relocating /app/node_modules/cwebp-bin/vendor/cwebp: __memcpy_chk: symbol not found
Error relocating /app/node_modules/cwebp-bin/vendor/cwebp: __vfprintf_chk: symbol not found
Error relocating /app/node_modules/cwebp-bin/vendor/cwebp: __sprintf_chk: symbol not found
Error relocating /app/node_modules/cwebp-bin/vendor/cwebp: __snprintf_chk: symbol not found
Error relocating /app/node_modules/cwebp-bin/vendor/cwebp: __longjmp_chk: symbol not found


  ⚠ cwebp pre-build test failed
  ℹ compiling from source
  ✔ cwebp built successfully
  ✔ pngquant pre-build test passed successfully
  ✔ optipng pre-build test passed successfully
  ⚠ Command failed: /app/node_modules/mozjpeg/vendor/cjpeg -version
Error relocating /app/node_modules/mozjpeg/vendor/cjpeg: __snprintf_chk: symbol not found
Error relocating /app/node_modules/mozjpeg/vendor/cjpeg: __memcpy_chk: symbol not found
Error relocating /app/node_modules/mozjpeg/vendor/cjpeg: __longjmp_chk: symbol not found
Error relocating /app/node_modules/mozjpeg/vendor/cjpeg: __fprintf_chk: symbol not found


  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c autoreconf -fiv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:23: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1


    at /app/node_modules/bin-build/node_modules/execa/index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
  ⚠ Response code 404 (Not Found)
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
```

**Notes**

**Comment by taniarascia** [comment]
Thanks for the report. Going to close this one and handle all Docker related issues in #454.
