### ISSUE TITLE
Unable to run in windows

### ISSUE THREAD

**Issue by passionate2023** [taniarascia/takenote#595]
Hi,

The steps are not working in windows 10 and have tried the same

Please help me with the steps to build or bundle

Thanks

**Comment by derin-art** [comment]
I have the same problem, the packages don't install with npm install, they just through errors like `npm ERR! gyp verb`. Is there anything I need to have apart from the latest node version before I install the packages. Thanks

**Comment by passionate2023** [comment]
npm run client
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> takenote@0.7.2 client
> cross-env NODE_ENV=development webpack serve --config config/webpack.dev.js

Getting environment variables from build args for production
(node:19796) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
i ｢wds｣: Project is running at http://localhost:3000/
i ｢wds｣: webpack output is served from undefined
i ｢wds｣: Content not from webpack is served from C:\Users\admin\Downloads\takenote-master\takenote-master
i ｢wds｣: 404s will fallback to /index.html
i ｢wdm｣: wait until bundle finished: /
(node:19796) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".
× ｢wdm｣: assets by info 13.8 MiB [immutable]
  assets by path *.png 1.59 MiB 3 assets
  assets by path *.svg 3.66 KiB
    asset 90beb9080e8c3ccb8565.svg 2.04 KiB [emitted] [immutable] (auxiliary name: main)
    asset 26da41caf83070639053.svg 1.61 KiB [emitted] [immutable] (auxiliary name: main)
  asset main.2ac20f49e2484e4b40c8.bundle.js 12.2 MiB [emitted] [immutable] (name: main)
assets by path *.html 836 bytes
  asset index.html 443 bytes [emitted]
  asset template.html 393 bytes [emitted] [copied]
asset logo512.png 44.7 KiB [emitted] [copied]
asset logo192.png 15.5 KiB [emitted] [copied]
asset favicon.ico 4.31 KiB [emitted] [copied]
asset manifest.json 505 bytes [emitted] [copied]
asset _redirects 23 bytes [emitted] [copied]
asset robots.txt 14 bytes [emitted] [copied]
runtime modules 25.1 KiB 14 modules
orphan modules 361 bytes [orphan] 1 module
modules by path ./node_modules/ 3.81 MiB
  javascript modules 3.81 MiB
    cacheable modules 3.81 MiB 700 modules
    2 modules
  json modules 2.03 KiB 3 modules
modules by path ./src/ 213 KiB (javascript) 1.59 MiB (asset)
  modules by path ./src/client/ 208 KiB 54 modules
  modules by path ./src/resources/ 5.33 KiB (javascript) 1.59 MiB (asset)
    asset modules 210 bytes (javascript) 1.59 MiB (asset) 5 modules
    javascript modules 5.12 KiB
      ./src/resources/LabelText.ts 1.63 KiB [built] [code generated]
      ./src/resources/TestID.ts 3.49 KiB [built] [code generated]
util (ignored) 15 bytes [built] [code generated]

ERROR in ./node_modules/codemirror/lib/codemirror.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].use[1]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[4].use[2]!./node_modules/codemirror/lib/codemirror.css)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at getDefaultSassImplementation (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\utils.js:43:10)
    at getSassImplementation (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\utils.js:57:30)
    at Object.loader (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\index.js:34:59)
 @ ./node_modules/codemirror/lib/codemirror.css 47:4-60:5 2:12-168 9:17-24 13:7-21 45:20-34 49:6-59:7 50:38-52 56:26-40 58:21-28 68:15-29
 @ ./src/client/containers/NoteEditor.tsx 18:0-40
 @ ./src/client/containers/TakeNoteApp.tsx 46:19-53
 @ ./src/client/containers/App.tsx 28:20-55
 @ ./src/client/index.tsx 19:12-39

ERROR in ./node_modules/codemirror/theme/base16-light.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].use[1]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[4].use[2]!./node_modules/codemirror/theme/base16-light.css)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at getDefaultSassImplementation (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\utils.js:43:10)
    at getSassImplementation (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\utils.js:57:30)
    at Object.loader (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\index.js:34:59)
 @ ./node_modules/codemirror/theme/base16-light.css 47:4-60:5 2:12-170 9:17-24 13:7-21 45:20-34 49:6-59:7 50:38-52 56:26-40 58:21-28 68:15-29
 @ ./src/client/containers/NoteEditor.tsx 19:0-44
 @ ./src/client/containers/TakeNoteApp.tsx 46:19-53
 @ ./src/client/containers/App.tsx 28:20-55
 @ ./src/client/index.tsx 19:12-39

ERROR in ./src/client/styles/index.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].use[1]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[4].use[2]!./src/client/styles/index.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at getDefaultSassImplementation (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\utils.js:43:10)
    at getSassImplementation (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\utils.js:57:30)
    at Object.loader (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\index.js:34:59)
 @ ./src/client/styles/index.scss 47:4-60:5 2:12-196 9:17-24 13:7-21 45:20-34 49:6-59:7 50:38-52 56:26-40 58:21-28 68:15-29
 @ ./src/client/index.tsx 23:0-30

webpack 5.1.3 compiled with 3 errors in 10061 ms
i ｢wdm｣: Failed to compile.

**Comment by kenglisch** [comment]
Take a look at the output you included. It says that the node-sass package is incompatible with your node js version and gives you clues on how to remedy your issue. Update node-sass to the version that supports whichever version of node js that you have installed.

Here's the support table from the node-sass npm package repo:

<html>
<body>


NodeJS | Supported node-sass version | Node Module
-- | -- | --
Node 19 | 8.0+ | 111
Node 18 | 8.0+ | 108
Node 17 | 7.0+, <8.0 | 102
Node 16 | 6.0+ | 93
Node 15 | 5.0+, <7.0 | 88
Node 14 | 4.14+ | 83


</body>
</html>

**Comment by passionate2023** [comment]
Now it gives the following error

[1] Error: error:0308010C:digital envelope routines::unsupported
[1]     at new Hash (node:internal/crypto/hash:71:19)
[1]     at Object.createHash (node:crypto:140:10)
[1]     at BulkUpdateDecorator.hashFactory (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\webpack\lib\util\createHash.js:138:18)
[1]     at BulkUpdateDecorator.update (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\webpack\lib\util\createHash.js:44:50)
[1]     at OriginalSource.updateHash (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\webpack\node_modules\webpack-sources\lib\OriginalSource.js:104:8)

**Comment by passionate2023** [comment]
C:\Users\admin\Downloads\takenote-master\takenote-master>node -e "console.log(require('node-sass').info)"
node-sass       8.0.0   (Wrapper)       [JavaScript]
libsass         3.5.5   (Sass Compiler) [C/C++]

**Comment by passionate2023** [comment]
Pls help me with the specific version details

1. Node js exact workable version
2. Sass exact workable version
3. libsaas exact workable version

I am getting lot of exceptions everytime

**Comment by kenglisch** [comment]
**To make this repo work:**

Try uninstalling your node js and installing `ver. 14.x`

The new error is unrelated to node-sass. Rather it's a node crypto package issue. With node `14.x` you should be able to run `npm i` without bumping any of the package versions. Make sure to revert all your changes and remove your local `node_modules` folder. Better yet, just start from scratch and re-clone the repo.

**Best advice:**

This repo needs to be updated. It's missing a lot of important security fixes because its packages are lagging behind. It would be best if you used the current node LTE, update the node-sass package to `8.0.0`, and see about fixing the crypto issue.

The issues you're experiencing aren't specific to Windows. It's a node + package incompatibility.

**Comment by passionate2023** [comment]
[1] ERROR in ./src/client/styles/index.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].use[1]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[4].use[2]!./src/client/styles/index.scss)
[1] Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
[1] Error: Cannot find module 'sass'
[1] Require stack:
[1] - C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\utils.js
[1] - C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\index.js
[1] - C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\cjs.js
[1] - C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\loader-runner\lib\loadLoader.js
[1] - C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\loader-runner\lib\LoaderRunner.js
[1] - C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\webpack\lib\NormalModule.js
[1] - C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\webpack\lib\LoaderTargetPlugin.js
[1] - C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\html-webpack-plugin\lib\child-compiler.js

**Comment by passionate2023** [comment]
I think it would be better if you can record a video separately for windows and linux environment so that it would be useful for many to follow the same steps

a. Windows 11
b. Windows 10
c. Linux

This would be really needed for anyone

**Comment by kenglisch** [comment]
`npm install sass`

Honestly, it sounds like you're attempting to drive a car having never seen one operate before. Your issues are "it's not moving!" people will ask "is the engine on?" and you ask "how do I start it?" then "how do I add fuel?" then "where do I put my key?" then "how do I shift?" then "you gave me bad instructions and I crashed" then "how do I fix a car?" then "you fix doesn't work and car is still broken." It's a lesson in futility.

You don't need a video. You need to get more experience using Node JS and NPM. Right now you're crowd sourcing answers to your issue instead of trying to solve them yourself. These are very basic errors. They're also errors that you're going to see regularly as packages age, lose maintainers, and fall into disrepair. There won't always be someone to hold your hand help you at every step. So, work through this one on your own. When you come across a message you don't understand, copy it and use Google to search for a solution.
