### ISSUE TITLE
Windows 64-bit error

### ISSUE THREAD

**Issue by passionate2023** [taniarascia/takenote#596]
npm i is success
npm run client is failed

ERROR in ./src/client/styles/index.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].use[1]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[4].use[2]!./src/client/styles/index.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\node-sass\lib\binding.js:13:13)

Full Error

Microsoft Windows [Version 10.0.19043.928]
(c) Microsoft Corporation. All rights reserved.

C:\Users\admin\Downloads\takenote-master\takenote-master>npm i
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

up to date, audited 2493 packages in 1m

96 vulnerabilities (36 moderate, 47 high, 13 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

C:\Users\admin\Downloads\takenote-master\takenote-master>npm run client
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> takenote@0.7.2 client
> cross-env NODE_ENV=development webpack serve --config config/webpack.dev.js

Getting environment variables from build args for production
(node:21464) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
i ｢wds｣: Project is running at http://localhost:3000/
i ｢wds｣: webpack output is served from undefined
i ｢wds｣: Content not from webpack is served from C:\Users\admin\Downloads\takenote-master\takenote-master
i ｢wds｣: 404s will fallback to /index.html
i ｢wdm｣: wait until bundle finished: /
(node:21464) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".
× ｢wdm｣: assets by info 13.8 MiB [immutable]
  assets by path *.png 1.59 MiB 3 assets
  assets by path *.svg 3.66 KiB
    asset 90beb9080e8c3ccb8565.svg 2.04 KiB [emitted] [immutable] (auxiliary name: main)
    asset 26da41caf83070639053.svg 1.61 KiB [emitted] [immutable] (auxiliary name: main)
  asset main.2ac20f49e2484e4b40c8.bundle.js 12.2 MiB [emitted] [immutable] (name: main)
assets by path *.html 836 bytes
  asset index.html 443 bytes [emitted]
  asset template.html 393 bytes [emitted] [copied]
asset logo512.png 44.7 KiB [emitted] [copied]
asset logo192.png 15.5 KiB [emitted] [copied]
asset favicon.ico 4.31 KiB [emitted] [copied]
asset manifest.json 505 bytes [emitted] [copied]
asset _redirects 23 bytes [emitted] [copied]
asset robots.txt 14 bytes [emitted] [copied]
runtime modules 25.1 KiB 14 modules
orphan modules 361 bytes [orphan] 1 module
modules by path ./node_modules/ 3.81 MiB
  javascript modules 3.81 MiB
    cacheable modules 3.81 MiB 700 modules
    2 modules
  json modules 2.03 KiB 3 modules
modules by path ./src/ 213 KiB (javascript) 1.59 MiB (asset)
  modules by path ./src/client/ 208 KiB 54 modules
  modules by path ./src/resources/ 5.33 KiB (javascript) 1.59 MiB (asset)
    asset modules 210 bytes (javascript) 1.59 MiB (asset) 5 modules
    javascript modules 5.12 KiB
      ./src/resources/LabelText.ts 1.63 KiB [built] [code generated]
      ./src/resources/TestID.ts 3.49 KiB [built] [code generated]
util (ignored) 15 bytes [built] [code generated]

ERROR in ./node_modules/codemirror/lib/codemirror.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].use[1]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[4].use[2]!./node_modules/codemirror/lib/codemirror.css)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at getDefaultSassImplementation (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\utils.js:43:10)
    at getSassImplementation (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\utils.js:57:30)
    at Object.loader (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\index.js:34:59)
 @ ./node_modules/codemirror/lib/codemirror.css 47:4-60:5 2:12-168 9:17-24 13:7-21 45:20-34 49:6-59:7 50:38-52 56:26-40 58:21-28 68:15-29
 @ ./src/client/containers/NoteEditor.tsx 18:0-40
 @ ./src/client/containers/TakeNoteApp.tsx 46:19-53
 @ ./src/client/containers/App.tsx 28:20-55
 @ ./src/client/index.tsx 19:12-39

ERROR in ./node_modules/codemirror/theme/base16-light.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].use[1]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[4].use[2]!./node_modules/codemirror/theme/base16-light.css)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at getDefaultSassImplementation (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\utils.js:43:10)
    at getSassImplementation (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\utils.js:57:30)
    at Object.loader (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\index.js:34:59)
 @ ./node_modules/codemirror/theme/base16-light.css 47:4-60:5 2:12-170 9:17-24 13:7-21 45:20-34 49:6-59:7 50:38-52 56:26-40 58:21-28 68:15-29
 @ ./src/client/containers/NoteEditor.tsx 19:0-44
 @ ./src/client/containers/TakeNoteApp.tsx 46:19-53
 @ ./src/client/containers/App.tsx 28:20-55
 @ ./src/client/index.tsx 19:12-39

ERROR in ./src/client/styles/index.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].use[1]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[4].use[2]!./src/client/styles/index.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at getDefaultSassImplementation (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\utils.js:43:10)
    at getSassImplementation (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\utils.js:57:30)
    at Object.loader (C:\Users\admin\Downloads\takenote-master\takenote-master\node_modules\sass-loader\dist\index.js:34:59)
 @ ./src/client/styles/index.scss 47:4-60:5 2:12-196 9:17-24 13:7-21 45:20-34 49:6-59:7 50:38-52 56:26-40 58:21-28 68:15-29
 @ ./src/client/index.tsx 23:0-30

webpack 5.1.3 compiled with 3 errors in 9359 ms
i ｢wdm｣: Failed to compile.

**Comment by kenglisch** [comment]
No need to create multiple tickets for the same issue. I provided a fix in your previous one.
